name: Deploy React App

on:
  push:
    branches:
      - main  # runs when you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v5

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22' # or whatever version you use

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy to EC2 using rsync
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avz --delete
          path: dist/             # or build/ for CRA
          remote_path: /var/www/demo-react
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
