# name: Deploy React App

# on:
#   push:
#     branches:
#       - main  # runs when you push to main

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted

#     steps:
#       # 1️⃣ Checkout the code
#       - name: Checkout code
#         uses: actions/checkout@v5

#       # 2️⃣ Setup Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v5
#         with:
#           node-version: '22'

#       # 3️⃣ Install dependencies
#       - name: Install dependencies
#         run: |
#           node -v
#           which node
#           npm install

#       # 4️⃣ Build project
#       - name: Build project
#         run: npm run build
        
#       - name: check ls status
#         run: |
#           echo "###############| copy to dest |####################"
#           sudo rsync -av --delete dist/ /var/www/demo-react/
#           echo "#####################################"
#           sudo chown -R root:root /var/www/demo-react
#           ls -la /var/www/demo-react
        

      # 5️⃣ Upload to EC2 as normal user into a temp folder
      # - name: Upload build to temp folder
      #   uses: burnett01/rsync-deployments@7.1.0
      #   with:
      #     switches: -avz --delete
      #     path: dist/
      #     remote_path: /var/www/demo-react/
      #     remote_host: ${{ secrets.EC2_HOST }}
      #     remote_user: ${{ secrets.EC2_USER }}
      #     remote_key: ${{ secrets.EC2_SSH_KEY }}


      # # 6️⃣ Move files to /var/www/demo-react with sudo (keeps root:root)
      # - name: Move to /var/www/demo-react with sudo
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo mkdir -p /var/www/demo-react
      #       sudo rsync -avz --delete /tmp/deploy/ /var/www/demo-react/
      #       sudo rm -rf /tmp/deploy


name: Deploy React App to EC2 via RSYNC

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 6️⃣ Deploy using RSYNC
      - name: Deploy with RSYNC
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./dist/ \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/demo-react/

      # 7️⃣ Set permissions and restart services
      - name: Set permissions and restart services
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo chown -R www-data:www-data /var/www/demo-react
            sudo chmod -R 755 /var/www/demo-react
            sudo systemctl reload nginx || sudo systemctl reload apache2 || true
            echo "Deployment completed!"
          EOF