name: Deploy React App

on:
  push:
    branches:
      - main  # runs when you push to main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v5

      # 2️⃣ Setup Node.js
      # - name: Setup Node.js
      #   uses: actions/setup-node@v5
      #   with:
      #     node-version: '22'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          whoami
          node -v
          npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build
        
      - name: check ls status
        run: |
          sudo rsync -av --delete dist/ /var/www/demo-react/
          sudo chown -R root:root /var/www/demo-react
          ls -la /var/www/demo-react
        

      # 5️⃣ Upload to EC2 as normal user into a temp folder
      # - name: Upload build to temp folder
      #   uses: burnett01/rsync-deployments@7.1.0
      #   with:
      #     switches: -avz --delete
      #     path: dist/
      #     remote_path: /var/www/demo-react/
      #     remote_host: ${{ secrets.EC2_HOST }}
      #     remote_user: ${{ secrets.EC2_USER }}
      #     remote_key: ${{ secrets.EC2_SSH_KEY }}


      # # 6️⃣ Move files to /var/www/demo-react with sudo (keeps root:root)
      # - name: Move to /var/www/demo-react with sudo
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo mkdir -p /var/www/demo-react
      #       sudo rsync -avz --delete /tmp/deploy/ /var/www/demo-react/
      #       sudo rm -rf /tmp/deploy