name: Deploy React App to EC2 with rsync

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          echo "install npm dependencies"
          npm install

      - name: Build React app
        run: |
         npm run build
         ls -lath
